### ISSUE TITLE
ISSUE WHILE TEST APPLICATION 

### ISSUE THREAD

**Issue by Amit006** [ashwamegh/razorpay-react-demo#16]
its throw msg like 
![issue](https://user-images.githubusercontent.com/8538903/89731050-b2858880-da61-11ea-9f99-dfa15a654cd2.png)

**Comment by ashwamegh** [comment]
@Amit006 Are you adding your API keys?

**Comment by ashwamegh** [comment]
I am closing this issue since it's not in progress. Feel free to open it in the future.
