### ISSUE TITLE
window.Razorpay is not a constructor 

### ISSUE THREAD

**Issue by abdulkadhir** [ashwamegh/razorpay-react-demo#3]
I got an error window.Razorpay is not a constructor 

`

   placeOrder(){

    let options = {
      "key": "RAZORPAY_KEY",
      "amount": this.state.amount, 
      "name": "Merchant Name",
      "description": "Purchase Description",
      "image": "/logo.png",
      "handler": function (response){
        alert(response.razorpay_payment_id);
      },
      "prefill": {
        "name": "xyz",
        "email": "123@xyz.com"
      },
      "notes": {
        "address": "Hello World"
      },
      "theme": {
        "color": "#F37254"
      }
    };
    
    const rzp = new window.Razorpay(options);
    rzp.open();

   }

<Button style={button_style}>    
       onClick={(e) => this.placeOrder()}
      color="primary" size="lg">Place order
     </Button>`

**Comment by rocknegi** [comment]
> I got an error window.Razorpay is not a constructor
> 
> `
> 
> placeOrder(){
> 
> ```
> let options = {
>   "key": "RAZORPAY_KEY",
>   "amount": this.state.amount, 
>   "name": "Merchant Name",
>   "description": "Purchase Description",
>   "image": "/logo.png",
>   "handler": function (response){
>     alert(response.razorpay_payment_id);
>   },
>   "prefill": {
>     "name": "xyz",
>     "email": "123@xyz.com"
>   },
>   "notes": {
>     "address": "Hello World"
>   },
>   "theme": {
>     "color": "#F37254"
>   }
> };
> 
> const rzp = new window.Razorpay(options);
> rzp.open();
> ```
> }
> >onClick={(e) => this.placeOrder()} color="primary" size="lg">Place order `

just add this to your index.html
> <script src="https://checkout.razorpay.com/v1/checkout.js"></script>

**Comment by ghost** [comment]
I got the same error. Just use 
```
const rzp = new window.Razorpay({key});
rzp.createPayment(options); // key not required
```

**Comment by ravipronteff** [comment]
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>

add in the HTML

**Comment by Sameer1408** [comment]
Thank u So much @rocknegi

**Comment by manishkumar-8218** [comment]
**_Thank u So much for providing solution@rocknegi_**

**Comment by Akshay7623** [comment]
Thank you @rocknegi

**Comment by AnittaMathew1** [comment]
I am getting same error for unit test TypeError: window.Razorpay is not a constructor
But the razorpay page is working fine.. error only in unit test using jest
