### ISSUE TITLE
Bad Gateway Error 

### ISSUE THREAD

**Issue by Darshan8990** [ashwamegh/razorpay-react-demo#4]
we are getting error **Failed to load resource: the server responded with a status of 400 (Bad Request)** when we try on 127.0.0.1 from local server , tried change value in front end .env url but same issue , first we tried on aws as well we are getting same issue when new page created in payment mode like netbanking or debit card . in upi qrcode its working fine. also tried on localhost in which everything working fine only giving issue on different ip...

**Comment by ashwamegh** [comment]
@Darshan8990 can you explain more about this scenario, I am not getting it properly

**Comment by ashwamegh** [comment]
@Darshan8990 If you're saying the your IP is not passing through the server. You can try adding your IP/URL in `allowedReferers` in `app.js` under server section.

**Comment by ashwamegh** [comment]
@Darshan8990  confirm this, So that I can mark this issue closed

**Comment by Darshan8990** [comment]
@ashwamegh nopp i tried changing the ip in app.js allowedReferers but its giving me same error payment declined when i try running on http://127.0.0.1:8080 in netbanking mode , its working properly in http://localhost:8080

**Comment by ashwamegh** [comment]
@Darshan8990 I can connect with you to solve this issue, if you want.

**Comment by savannahar68** [comment]
@ashwamegh @Darshan8990  i'm facing same issue.
Were you able to resolve this?

So when I try doing any sort of payment in live mode locally(localhost) it works fine!
But when I try the same using AWS, I get : 
https://api.razorpay.com/v1/payments/create/ajax 400 (Bad Request)

With response from Razorpay api as :

{"error":{"code":"BAD_REQUEST_ERROR","description":"Payment declined","metadata":{"payment_id":"pay_Ei0SzjnTxiQBYr"}}}

**Comment by savannahar68** [comment]
@Darshan8990 maybe it's because razorpay checks for the website you have registered with them while making payment, if they are not same then it'll throw this error.

This resolved the issue for me.

**Comment by Darshan8990** [comment]
Thanks ill check and confirm..

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ashwamegh** [comment]
@savannahar68 @Darshan8990 Thanks for confirming it, I am closing this issue for now. If something comes up, feel free to reopen it.
